version: '3'

services:
  identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
  angular-spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    