version: '2'

services:
  proxy:  
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    - ./certs:/etc/nginx/certs:ro
    - /etc/nginx/vhost.d
    - /usr/share/nginx/html
    links:
    - identityserver
    - webapi
    - angular-spa

  proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certs:/etc/nginx/certs:rw
    - ./vhost.d:/etc/nginx/vhost.d:rw
    - ./html:/usr/share/nginx/html:rw
    environment:
    - NGINX_PROXY_CONTAINER=proxy

  identityserver:
    image: bmantay/identityserver
    environment:
    - WEBAPI=https://api.brianmantay.com
    - ANGULAR_SPA=https://spa.brianmantay.com
    - VIRTUAL_PORT=443

  webapi:
    image: bmantay/webapi
    environment:
    - VIRTUAL_HOST=api.brianmantay.com
    - VIRTUAL_PORT=443
    links:
    - identityserver

  angular-spa:
    image: bmantay/angular-spa
    links:
    - identityserver
    - webapi
    environment:
    - WEBAPI=https://api.brianmantay.com
    - ANGULAR_SPA=https://spa.brianmantay.com
    - IDENTITY_AUTHORITY=https://id.brianmantay.com
    - VIRTUAL_HOST=spa.brianmantay.com
    - VIRTUAL_PORT=443
