version: '2'

services:
  identityserver:
    image: bmantay/identityserver
    ports:
    - "5000:80"
    environment:
    - WEBAPI=http://acs-identityserver.eastus.cloudapp.azure.com:5001
    - ANGULAR_SPA=http://acs-identityserver.eastus.cloudapp.azure.com:4200

  webapi:
    image: bmantay/webapi
    ports:
    - "5001:80"
    links:
    - identityserver

  angular-spa:
    image: bmantay/angular-spa
    ports:
    - "4200:80"
    links:
    - identityserver
    - webapi
    environment:
    - WEBAPI=http://acs-identityserver.eastus.cloudapp.azure.com:5001
    - ANGULAR_SPA=http://acs-identityserver.eastus.cloudapp.azure.com:4200
    - IDENTITY_AUTHORITY=http://acs-identityserver.eastus.cloudapp.azure.com:5000
