version: '2'

services:
  identityserver:
    build:
      context: ./identityserver
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - WEBAPI=http://localhost:5001
    - ANGULAR_SPA=http://localhost:4200

  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    
  angular-spa:
    build:
      context: ./angular-spa
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - WEBAPI=http://localhost:5001
    - ANGULAR_SPA=http://localhost:4200
    - IDENTITY_AUTHORITY=http://localhost:5000
      