version: '2'

services:
  proxy:  
    image: jwilder/nginx-proxy
    ports:
    - "80:80"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
    links:
    - identityserver
    - webapi
    - angular-spa

  identityserver:
    image: bmantay/identityserver
    environment:
    - WEBAPI=http://api.brianmantay.com
    - ANGULAR_SPA=http://spa.brianmantay.com

  webapi:
    image: bmantay/webapi
    environment:
    - VIRTUAL_HOST=api.brianmantay.com
    links:
    - identityserver

  angular-spa:
    image: bmantay/angular-spa
    links:
    - identityserver
    - webapi
    environment:
    - WEBAPI=http://api.brianmantay.com
    - ANGULAR_SPA=http://spa.brianmantay.com
    - IDENTITY_AUTHORITY=http://id.brianmantay.com
    - VIRTUAL_HOST=spa.brianmantay.com
