version: '3'

services:
  identityserver:
    image: bmantay/identityserver
    ports:
      - "5000:80"

  webapi:
    image: bmantay/webapi
    ports:
      - "5001:80"
    links:
      - identityserver

  angular-spa:
    image: bmantay/angular-spa
    ports:
      - "4200:80"
    links:
      - identityserver
      - webapi
