version: '2'

services:

  identityserver:
    build:
      context: ./identityserver
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - WEBAPI=http://api.domain.com
    - ANGULAR_SPA=http://spa.domain.com
    - VIRTUAL_HOST=id.domain.com

  webapi:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - VIRTUAL_HOST=api.domain.com
    
  angular-spa:
    build:
      context: ./angular-spa
      dockerfile: Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - WEBAPI=http://api.domain.com
    - ANGULAR_SPA=http://spa.domain.com
    - IDENTITY_AUTHORITY=http://id.domain.com
    - VIRTUAL_HOST=spa.domain.com
      